apiVersion: v2
description: Install traefik
maintainers:
- name: Sascha
name: traefik
dependencies:
- name: traefik
  version: 38.0.1
  repository: "https://traefik.github.io/charts"
type: application
version: 1.0.0
