apiVersion: v2
description: Install RabbitMQ
maintainers:
- name: Sascha
name: rabbitmq
dependencies:
- name: rabbitmq
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - rabbitmq
  version: 16.0.14
type: application
version: 1.0.0
